app:
  name: app
  group: app
  replicaCount: 1
  container:
    image: wkrzywiec/kanban-ui:k8s
    port: 8080
    config: []
    env: 
      - key: key
        value: value
  service:
    type: ClusterIP
    port: 8080
